pipelines:
  default:
    - step:
        image: python:3.7.1
        script:
          - pip install -r requirements.txt
          - python manage.py test
        caches:
          - pip
        services:
            - rabbitmq
    - step:
        image: node:10.16.0
        script:
          - yarn install
          - yarn run build
        caches:
          - node


definitions:
  services:
    rabbitmq:
      image: rabbitmq
      environment:
        RABBITMQ_ERLANG_COOKIE: "FDASFASAFDASFWEFGSDF"
        RABBITMQ_DEFAULT_USER: "guest"
        RABBITMQ_DEFAULT_PASS: "guest"
        RABBITMQ_DEFAULT_VHOST: "/"
