image: python:3.7.1
pipelines:
  default:
    - step:
        script:
          - pip install -r requirements.txt
          - python manage.py test
        caches:
          - pip
        services:
            - rabbitmq

definitions:
  services:
    rabbitmq:
      image: rabbitmq
      environment:
        RABBITMQ_ERLANG_COOKIE: "FDASFASAFDASFWEFGSDF"
        RABBITMQ_DEFAULT_USER: "guest"
        RABBITMQ_DEFAULT_PASS: "guest"
        RABBITMQ_DEFAULT_VHOST: "/"
