# Generated by Django 2.0.7 on 2019-02-28 13:26

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sort_name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100, null=True, verbose_name=[('Character', 'Character'), ('Choir', 'Choir'), ('Group', 'Group'), ('Orchestra', 'Orchestra'), ('Other', 'Other'), ('Person', 'Person')])),
                ('gender', models.CharField(default='None', max_length=6, verbose_name=[('Female', 'Female'), ('Male', 'Male'), ('None', 'None')])),
                ('area', models.CharField(blank=True, max_length=100)),
                ('begin', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
                ('alias', models.CharField(blank=True, max_length=100)),
                ('mbid', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField(blank=True)),
                ('country', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('catalogue_number', models.CharField(max_length=100)),
                ('barcode', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=14, verbose_name=[('Bootleg', 'Bootleg'), ('Official', 'Official'), ('Promotional', 'Promotional'), ('Pseudo-Release', 'Pseudo-Release')])),
                ('mbid', models.CharField(blank=True, max_length=100)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlists.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('length', models.DurationField()),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='playlists.Release')),
                ('stream_sources', jsonfield.fields.JSONField(default=[])),
                ('mbid', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='release',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='release',
            name='barcode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
