# Generated by Django 2.0.7 on 2018-07-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sort_name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Character', 'Character'), ('Choir', 'Choir'), ('Group', 'Group'), ('Orchestra', 'Orchestra'), ('Other', 'Other'), ('Person', 'Person')], max_length=100)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('None', 'None')], max_length=6)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('begin', models.DateTimeField(blank=True)),
                ('end', models.DateTimeField(blank=True)),
                ('ipi', models.CharField(blank=True, max_length=100)),
                ('isni', models.CharField(blank=True, max_length=100)),
                ('alias', models.CharField(blank=True, max_length=100)),
                ('mbid', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
