# Generated by Django 2.0.7 on 2018-07-29 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_auto_20180724_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('length', models.DurationField()),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlists.Release')),
            ],
        ),
    ]
