# Generated by Django 2.0.7 on 2019-01-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0005_auto_20180918_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='mbid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='release',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
