# Generated by Django 2.0.7 on 2019-01-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0007_auto_20190118_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='begin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='end',
            field=models.DateTimeField(null=True),
        ),
    ]
