# Generated by Django 2.0.7 on 2019-01-18 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0008_auto_20190118_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='type',
            field=models.CharField(max_length=100, null=True, verbose_name=[('Character', 'Character'), ('Choir', 'Choir'), ('Group', 'Group'), ('Orchestra', 'Orchestra'), ('Other', 'Other'), ('Person', 'Person')]),
        ),
    ]
